### ISSUE TITLE
WAWebTransfer: "NameError: name 'driver' is not defined"

### ISSUE THREAD

**Issue by Gilduuw** [jeliebig/WAWebSessionHandler#1]
Hey,

Your tool seemed like a great idea to package and run Whatsapp Web session files.  

So, I copied the files WADisplay and WAWebTransfer to run them as a management command.

When running WAWebTransfer, I am getting the following error:

File "C:\Users\gille\timeless_wisdom\timeless_wisdom\management\commands\WAWebTransfer.py", line 6, in handle
    WAWebTransfer()
  File "C:\Users\gille\timeless_wisdom\timeless_wisdom\views\whatsapp.py", line 200, in WAWebTransfer
    **for key, value in get().items():**
  File "C:\Users\gille\timeless_wisdom\timeless_wisdom\views\whatsapp.py", line 162, in get
    **return driver.execute_script("""**
**NameError: name 'driver' is not defined**

Do you have any idea how I could resolve this?

Just to clarify:
- I have all the requirements installed
- I am running on py2.exe 64-bit... But don't think that's the issue here.

Many thanks, it's much appreciated!! 
Gilles

**Comment by jeliebig** [comment]
Hey,

Thank you for using my tool, nice to hear that someone can use it.
I couldn't reproduce the error on my machine by only using the script. Are you running your compiled version?

driver is the object for the running webdriver from selenium, normally there should be no error.
The only thing i can think about now is a problem with the webdriver.
Did you use the latest releases of chromedriver and geckodriver?
And make sure that they are in the same directory as the script or in your PATH.

Sorry for my late answer and thanks for posting your issue.

Julian

**Comment by jeliebig** [comment]
Hey again,

I reworked my script completely and the bug should be fixed with that.

Thanks for opening the issue!

Julian
