### ISSUE TITLE
not working any more

### ISSUE THREAD

**Issue by shirser121** [jeliebig/WaWebSessionHandler#3]
its work fine to me, but today I found out that Whatsapp Web does not recognize me anymore

**Comment by Maurel19** [comment]
Until yesterday, February 24, it worked fine

**Comment by shirser121** [comment]
Hi. I know. Yesterday its work for me, but today its not working at all.
Can you check this please?

**Comment by jeliebig** [comment]
Hello,
Somehow I missed the notification. Sorry for not answering for so long.
Could you tell me a bit more about the problem you face?
I will look at my script in a few minutes and verify that everything is still working and if not I will fix the issue of course.

Sorry again for letting you guys wait for so long.

**Comment by jeliebig** [comment]
Jup, you are right. They changed their session saving method back to the old one. They are still storing everything in the new format, but seem ignore it now.
That should be a quick fix. I'll let you guys know as soon as I pushed the changes to Github.

**Comment by jeliebig** [comment]
In case my solution doesn't work for you guys, feel free to reopen this issue!
